apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: ms-dormir
  name: ms-dormir
  namespace: toolkit
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: ms-dormir
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.network/springcloud: "true"
        io.kompose.service: ms-dormir
    spec:
      containers:
      - image: 96552333aa/ms-dormir:v1
        imagePullPolicy: Always
        name: ms-dormir
        ports:
        - containerPort: 8001
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ventas
      serviceAccountName: ventas
      terminationGracePeriodSeconds: 30
      
